# Site settings
title: restic - backups done right
description: > # this means to ignore newlines until "baseurl:"
  restic is a program that does backups right. IT's easy, fast, secure and
  efficient, and the backups are verifiable!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://restic.github.io" # the base hostname & protocol for your site
github_username: restic

# Build settings
markdown: kramdown

# enable GitHub Flavoured Markdown
kramdown:
  input: GFM
